### ISSUE TITLE
No devices listed

### ISSUE THREAD

**Issue by smarial** [yenoiwesa/homebridge-connexoon#10]
Hi,

after installing the plugin, i cannot get any devices. There is also no error in the logs.
Only:

[2020-6-4 23:38:41] [My Connexoon] Initializing Connexoon platform...
[2020-6-4 23:38:41] [My Connexoon] Connexoon Init

Using the same credentials with the homebridge-tahoma gives me the right devices from the connexoon box.

What is wrong?

Best,
Alexandre

**Comment by yenoiwesa** [comment]
Hi @smarial,

Did you specify the correct `service` in the platform configuration as per the README file? `homebridge-tahoma` and `homebridge-connexoon` have different default services.

If that doesn't help, please start your homebridge server with the `-D` debug log level option to get more details.

Let me know how that goes.

**Comment by smarial** [comment]
Hi,

Both are on „TaHoma“ as the „Connexoon“ or „ConnexoonRTS“ were not working.
I will run homebridge in debug mode and let you know

**Comment by smarial** [comment]
Hi,
struggeling to get debugging working.
Over UI pluging the debug option gave nothing additional in the logs for our plugin.
Using DEBUG=* in /etc/default/homebridge gave tons of logs that i was not really able to cluster.
What would be the right way to find something helping to understand?

**Comment by yenoiwesa** [comment]
What type of devices do you have connected to the Connexoon bridge @smarial ?

**Comment by smarial** [comment]
i have a blind.
There are 2 other objects somehow registered on the bridge coming from the previous owner of the bridge. I can see them when using homebridge-tahoma (Garage and Box). Unfortunately, i cannot delete them.

**Comment by yenoiwesa** [comment]
Sorry @smarial but I will need more details. Running Homebridge in debug mode you should see an entry that states:
```
Ignored device of type {X}
```
...if a device was skipped during initialisation of the platform.

You should at least see that in your logs when you restart your homebridge server.

Maybe just try to start homebridge without the Homebridge UI, directly from CLI?

**Comment by yenoiwesa** [comment]
Since you haven't updated this issue in 2 weeks I assume your problem is resolved? I will close the issue for now.
