### ISSUE TITLE
Support stopping open/close sequence via a switch

### ISSUE THREAD

**Issue by yenoiwesa** [yenoiwesa/homebridge-connexoon#11]
Suggested in #9, the suggestion is to support an additional switch that would send a message to the Connexoon server to stop the current command, allowing to stop the opening/closing of the shades at the desired height.

**Comment by BarnicleFiend** [comment]
A stop command would be extremely useful for me. I have 2x windows over 3m high and rarely have them fully open or fully closed. There is a stop command in the connexoon app, so presumably this can be mapped to a switch somehow?

I also have 2x window openers which open very far, so I always have them either fully closed or partially open. The my position doesn’t work for them for some reason (presumably hardware related). 

It would be great to set the windows up as windows, they are set up as roller blinds currently to allow HomeKit control.

**Comment by yenoiwesa** [comment]
Hey @BarnicleFiend, regarding a stop command, the issue is that I do not know how to implement it in a way that makes sense right now.

Should it be one switch that stops all the blinds that have an active command? Should it be one switch per blind? How do I name these switches?

If you have any suggestions please be welcome to share them.

Regarding your window mapping issue, could you please raise a separate ticket? If you could also start your homebridge server in debug mode while your Somfy Window is mapped as window, you should see a log entry that reads:

```
Ignored device of type X
```

I need to know what that `X` is to map it accordingly.

Thanks.

**Comment by BarnicleFiend** [comment]
Hi, A switch that stops all active commands would be perfect for me. Happy to help test this if that would be helpful.

I have a toggle button set to open and close blind and window in each room and the key functionality missing for me is stop. The ideal programming for me would be single press toggle open / close blind. Long press toggle open / close window. Double press stop anything active.

I’ve got the open / close toggle settings sorted but still have to keep a remote handy to stop.

I’ll roll the window mapping into another ticket.

**Comment by yenoiwesa** [comment]
Sorry @BarnicleFiend I have thought a long time about this and I cannot think of a nice way to make this behave. There would always be a desynchronisation between the state reported and the actual state of the blind.

Overall, I think this should not be a feature of the plugin as it would be too confusing to use. I will not implement this feature.
