### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by rubenstolk** [yenoiwesa/homebridge-connexoon#16]
I was hoping that this plugin provides more native functionality than this one: https://github.com/dubocr/homebridge-tahoma#readme but the credentials that work for the latter (using a connexoon device) don't work on this plugin.

**Comment by yenoiwesa** [comment]
Hi @rubenstolk 👋 

Both plugins use the same credentials, please make sure to select the `service` configuration that corresponds to your geographical region. There are four options, test all four if you don't know which one is correct for your region.

**Comment by rubenstolk** [comment]
Oh ok! Then that must be the problem. Thanks for the quick answer!

**Comment by yenoiwesa** [comment]
I just updated the README file to clarify that the `service` option is what can cause login errors. I also listed `service` as a mandatory setting entry (although it is not technically the case).

**Comment by rubenstolk** [comment]
![alf](https://user-images.githubusercontent.com/692644/85674447-22fc6400-b6c5-11ea-860d-2fb1320c4f4a.gif)
