### ISSUE TITLE
Unable to login. Error msgs attached. Username/Password confirmed correct and working.

### ISSUE THREAD

**Issue by BladesKnight** [yenoiwesa/homebridge-connexoon#17]
```
[7/6/2020, 2:42:41 PM] [My Connexoon Hub] Could not login with any of the authentication methods.
[7/6/2020, 2:42:41 PM] [My Connexoon Hub] Failed to get device list undefined
[7/6/2020, 2:42:41 PM] [My Connexoon Hub] Could not login with any of the authentication methods.
```

Any ideas?
Thanks.

**Comment by yenoiwesa** [comment]
Hi @BladesKnight,

Did you have a look at the closed issues?
https://github.com/yenoiwesa/homebridge-connexoon/issues?q=is%3Aissue+is%3Aclosed

Basically: please read the README file entirely and make sure you have selected the right "service" config.

Thanks.

**Comment by BladesKnight** [comment]
Have already tried all 4 (Cozytouch, TaHoma, Connexoon or ConnexoonRTS) and all 4 gives the same error.

**Comment by yenoiwesa** [comment]
Then there must be an issue with your credentials. What is your geographical region and can you login with the same credentials on the Somfy website?

**Comment by BladesKnight** [comment]
Was able to use the same credentials successfully with homebridge-tahoma v0.3.50 and using the service "Connexoon RTS". I am in Asia/Singapore.

**Comment by yenoiwesa** [comment]
Both projects use the same login mechanism and credentials. 

Could you try again with the same service you use for homebridge tahoma? 

Singapore uses the same servers as Australia and I can confirm that the credentials work fine using the ConnexoonRTS service.

**Comment by BladesKnight** [comment]
Tried and got the same error msgs. It might be something or nothing but the service is "Connexoon RTS" on homebridge tahoma but on your readme, its "ConnexoonRTS".

**Comment by stereo247** [comment]
I tried and am having similar issues with a different output error:
Error: The requested platform 'TaHoma' was not registered by any plugin.
    at PluginManager.getPluginForPlatform

**Comment by yenoiwesa** [comment]
@BladesKnight it's correct that the enum value is different in the two projects. In this plugin it's indeed `ConnexoonRTS`, which is also the default value for `service`.

Could you please start your homebridge server in debug mode with the option `-D` in the command line? That should provide additional logging.

**Comment by yenoiwesa** [comment]
@BladesKnight have you eventually fixed your authentication problem?

**Comment by yenoiwesa** [comment]
Closing as no response.
