### ISSUE TITLE
"Connexoon" not registered

### ISSUE THREAD

**Issue by BarnicleFiend** [yenoiwesa/homebridge-connexoon#20]
Hi,

Since the latest update my accessories have disappeared and I get the following log error:
```
30/08/2020, 14:02:13 The requested platform "Connexoon" was not registered by any plugin.
30/08/2020, 14:02:13 Your config.json is requesting the platform "Connexoon" which has not been published by any installed plugins.
```

If I clear my config code for connexoon it crashes HomeBridge.

**Comment by yenoiwesa** [comment]
Hi @BarnicleFiend 👋 

Could you check what version of homebridge you are running? With the latest version I bumped the required homebridge dependency to be version 1.0.0 or above.

**Comment by BarnicleFiend** [comment]
Thanks for the reply. I’m running on HOOBS which I think uses a custom version of homebridge. Is that the issue?

**Comment by yenoiwesa** [comment]
To be honest I have no idea about how HOOBS differs from a vanilla homebridge install.

Could you share your config file in here (redacting any credentials)?

**Comment by BarnicleFiend** [comment]
Sure:
```json
{
    "platform": "Connexoon",
    "name": "My Connexoon Hub",
    "service": "Connexoon",
    "username": "XXX",
    "password": "XXX",
    "devices": {
        "Master Bedroom Blind": {
            "commands": [
                "close",
                "my",
                "open"
            ]
        },
        "Bedroom Blind": {
            "commands": [
                "close",
                "my",
                "open"
            ]
        },
        "Master Bedroom Window": {
            "commands": [
                "close",
                "my",
                "open"
            ]
        },
        "Bedroom Window": {
            "commands": [
                "close",
                "my",
                "open"
            ]
        }
    }
}
```

**Comment by BarnicleFiend** [comment]
Is there a command I can put into terminal to get the homebridge version?

**Comment by yenoiwesa** [comment]
> Is there a command I can put into terminal to get the homebridge version?

There doesn't seem to be a way to do that because HOOBS uses a modified version of homebridge.

Your configuration looks fine. By the way, you can drop the `devices` section entirely because you are just mapping them to the default set of commands, so it's the same as just having:

```
{
    "platform": "Connexoon",
    "name": "My Connexoon Hub",
    "service": "Connexoon",
    "username": "XXX",
    "password": "XXX",
}
```

I have searched online and found that other people are encountering similar issues with HOOBS. Could you try re-installing the plugin from scratch via the HOOBS UI?
HOOBS seems to not be finding the platform plugin.

**Comment by yenoiwesa** [comment]
@BarnicleFiend I have found a similar issue being resolved in another plugin: https://github.com/schemers/homebridge-screenlogic/commit/84c9e1ad7c30ea9fea4ad879be1d3f5f7e165c34

In the homebridge changelog, version 1.0.0 introduced the following method signature change:
> The signatures of registerAccessory and registerPlatform have been adjusted. The plugin name, which was passed as the first argument, can now be left out and will be determined automatically by homebridge.

...which I embraced in my plugin, but it seems HOOBS is not compliant with that new signature. So I will add back the plugin name as first parameter. Will let you know once the new version is published.

**Comment by yenoiwesa** [comment]
@BarnicleFiend I just released version `2.1.1` of the plugin. Could you try with this latest version?

**Comment by BarnicleFiend** [comment]
That’s all working normally again, thanks @yenoiwesa. Really appreciate your efforts.

**Comment by yenoiwesa** [comment]
That's great news, thanks for raising this @BarnicleFiend !
