### ISSUE TITLE
Latest API has exchange "my" for "stop"

### ISSUE THREAD

**Issue by jdebardi** [yenoiwesa/homebridge-connexoon#24]
Just installed this and was having trouble getting the blinds to go to the 'my' position.

Turns out if the capabilities returned are 'open', 'close', 'identify' and 'stop' - no sign of 'my'!
I used Somfy's online API tester to work this out - https://developer.somfy.com/somfy-open-api/apis

No idea if this is specific to my model or if it's the lates test iteration of the API dropping the 'my' in place of 'stop', but setting the command string accordingly fixed it...
"commands": ["close", "stop", "open"]

Might be worth updating the README at the very least to suggest this as a possibility for some users.

**Comment by yenoiwesa** [comment]
Hi @jdebardi 👋 

Just to be clear, are you saying that `stop` as a command will still move your blind to the preferred **My** position of the blind? That seems quite strange.

My blinds are setup with a specific **My** position and the blinds do go to that position with the default commands array when I move the slider to 50%.

Could you please let me know what is your:
- geographic area,
- Connexoon bridge type/model,

...and confirm that your blinds use the RTS protocol, not the IO one?

Thanks.

**Comment by jdebardi** [comment]
Hi.

Yes. The command "stop" moves them to the "my" position.

I have Tilt Only 50 WireFree RTS Venetian blinds. Using a TaHoma hub (it updated to the latest firmware as I installed it), in the UK.

All of Somfy's documentation refers to STOP/My as a collective "same thing".￼ So in that way I guess it makes sense.
See here https://service.somfy.com/downloads/nam_v4/tilt50_programming_instructions_may_2016.pdf

Either Somfy have purposely dropped the "my" capability from my model or forgot to include both "my" and "stop" as aliases of each other in the API?

I'm grateful that the plug-in configuration allows for custom commands at least!

**Comment by yenoiwesa** [comment]
> Yes. The command "stop" moves them to the "my" position.

That is quite strange to be honest.

> Turns out if the capabilities returned are 'open', 'close', 'identify' and 'stop' - no sign of 'my'!
I used Somfy's online API tester to work this out - https://developer.somfy.com/somfy-open-api/apis

This is not the actual API that the plugin uses. The plugin uses a similar but internal API (Overkiz API) used by the iOS and Android Somfy apps. It doesn't use the Somfy domain either.

> All of Somfy's documentation refers to STOP/My as a collective "same thing".￼ So in that way I guess it makes sense.
See here https://service.somfy.com/downloads/nam_v4/tilt50_programming_instructions_may_2016.pdf

I don't think that the end user documentation on button mapping is indicative of the way the Connexoon/TaHoma API is working.

It might work to map the `stop` command this way but I have never tested it. That is also the first report I am hearing of this behaviour. My roller blinds do support the `stop` capability but that's in addition of the `my` capability.

**Comment by jdebardi** [comment]
Mine support open and close as well.
I've chosen to configure it with close and stop only so that Siri/HomeKit view open as 'my' position.

It all works really well aside from the once an hour issue I mention in a new issue.

**Comment by yenoiwesa** [comment]
Sorry I meant `stop` not `close`, I will edit my previous message.

**Comment by yenoiwesa** [comment]
As per this comment in a different issue: https://github.com/yenoiwesa/homebridge-connexoon/issues/25#issuecomment-770456025

the problem could have been caused by a misconfiguration of the blind during setup? Unclear but the issue seems to have disappeared for now.

Please reopen the issue if the problem happens again.
