### ISSUE TITLE
Gate control

### ISSUE THREAD

**Issue by schizza** [yenoiwesa/homebridge-connexoon#31]
Hi, is it possible to add control for gate control? It is IO system, but is able to receive RTS from Keypad, so I suppose this could work?

**Comment by yenoiwesa** [comment]
Hey @schizza, do you have more details about the RTS commands that need to be sent to the Connexoon API? I don't have the hardware to test with.

Also if your device supports IO protocol I really recommend to use an IO plugin like [Homebridge Tahoma](https://github.com/dubocr/homebridge-tahoma). I think knowing the state of a gate is rather important. With RTS the plugin can only guess it.

**Comment by yenoiwesa** [comment]
@schizza I will now close this issue.
