### ISSUE TITLE
Multiple connexoons on one homebridge instance

### ISSUE THREAD

**Issue by woodgieboodgie** [yenoiwesa/homebridge-connexoon#38]
hello,

great plugin, works a treat.

curious as to whether i can purchase multiple connexoons to handle a second and third story that the current connexoon cannot reach.  will the plugin handle three (assuming the additional ones have a unique email address)?
concrete separates the floors.

**Comment by yenoiwesa** [comment]
Hi @woodgieboodgie 👋 

That's an interesting scenario.

At the moment, the plugin won't support it as it's registered as a Homebridge platform and only one platform can be added of each type. So I would need to add support to connecting multiple Somfy accounts in the plugin itself.

However, now I wonder how Somfy handles that scenario in a vanilla, non-Homebridge, setup. Surely they would not ask you to have multiple Somfy accounts. You wouldn't even be able to use their official app to control your shades as you can only login with one account at a time.

Have you discussed with your Somfy installer/partner about it? Are you sure that the Connexoon wouldn't reach your first and third floor shades if it is installed on the second floor?

The [Connexoon PDF](https://nomadblinds.com.au/wp-content/uploads/2018/04/Connexoon-Window-RTS-Datasheet.pdf) indicates the following range for the box:

> 200 metres in open field,
> 20 metres through 2 reinforced concrete walls

Somfy sells RTS signal repeaters, and I think that's probably a better option: https://www.somfysystems.com/en-us/products/1810791/rts-repeater

**Comment by woodgieboodgie** [comment]
https://www.somfypro.com.au/find-a-product/-/e-cat/1810803 is Somfy's RS485 RTS transmitter.  Believe they need power and are hard wired to upmarket controllers.

Have queried Somfy tech support re the repeater you listed above but not sure its available in AU.  Will circle back with their response.

**Comment by yenoiwesa** [comment]
@woodgieboodgie since I am not going to add multi account support to the plugin, I will be closing this issue.

Don't hesitate to add the results of your findings regarding RTS signal extenders for other users who might run into a similar issue.

Cheers,
