### ISSUE TITLE
Cannot connect in North American region

### ISSUE THREAD

**Issue by sprihar** [yenoiwesa/homebridge-connexoon#39]
Hi,

Trying to connect to my RTS blinds using Tahoma. Im located in Canada and utilize the Somfy 'TahomaNorthAmerica' app. Have tried every available option in the 'service' config, however no luck. Using the same credentials to login to the Tahoma North America app. Is there something I am missing?

Thank you

**Comment by yenoiwesa** [comment]
Hi @sprihar, I see you have raised a similar issue in https://github.com/dubocr/homebridge-tahoma/issues/357

Unfortunately I do not know if there is a new service that Somfy has deployed for the North American region. I will watch updates on the other ticket you created as I don't know how to discover new services myself.

Sorry for not being of much help! I will keep this issue open.

**Comment by jonathanwilner** [comment]
I’ve battled this for months. This service doesn’t work for North America as far as I can tell. I’ve tried to escalate through Somfy North America re: both the right login + the overall stated & removed support for HomeKit in North America and gotten precisely nowhere. 

I can get the HomeAssistant Tahoma stuff to work, but very inconsistently - same as the unreliability of the iOS app that has long timeouts and errors.

I’d love any tips for alternate RTS methods  / remotes / hubs that work with HomeKit / HomeBridge that don’t rely on Somfy’s Internet services.

**Comment by yenoiwesa** [comment]
@jonathanwilner well I have actually stopped using the Somfy Connexoon to control my shades myself because it was too slow and unreliable... and that is in the Australia/APAC region where they don't offer any other solution.

I am now using this solution that requires a bit of component soldering and a Raspberry Pi: https://github.com/Nickduino/Pi-Somfy
All the instructions to get your very own remote working are in the repo's README file.

Then I adapted this Connexoon homebridge plugin to work with the above project's Python server API instead: https://github.com/yenoiwesa/homebridge-somfy-pi

I have not released this plugin on npm. Actually I just made it public right now, I was keeping it as private because it's a very bespoke need.

Here is my Somfy Raspberry Pi remote:
![B6CA592F-B9EA-4FC6-8694-3F06BA34DFFD_1_105_c](https://user-images.githubusercontent.com/1464666/151246487-3683952a-04d3-483d-8224-e7f3d8b8c855.jpeg)

It's working absolutely beautifully, it is very reliable, and much faster than with the Connexoon.
The caveat is the soldering involved and that I have a server to keep running (which I had to already for Homebridge).

Let me know if that helps!

**Comment by jonathanwilner** [comment]
Thank you for sharing that! I am leery of soldering but that looks awesome! Desperate times may call for desperate measures. :-)

**Comment by plo2022** [comment]
Hello - very new to this and have set up the Connexoon plugin but keep getting the following message - Username and password must be defined as configuration. I'm in AU. Any pointers on the plugin config?
Thanks Peter

**Comment by yenoiwesa** [comment]
Hi @plo2022, 

It would have been better to create a new issue for your problem as it's not related to the current issue of this thread.

But either way, have you setup your username and password in the HomeBridge configuration JSON file as indicated in the README file?

**Comment by plo2022** [comment]
Sorry about that - let me know if I still should. In answer to your question, yes, I have added username and pw - I copied the script as below
```json
{
    "bridge": {
        "...": "..."
    },
    "description": "...",
    "platforms": [
        {
            "platform": "Connexoon",
            "name": "My Connexoon Hub",
            "username": "<xxxxx@xxx.com>",
            "password": "<123456789>",
            "service": "Connexoon"
        }
    ],
    "platform": "Connexoon"
}
```

**Comment by yenoiwesa** [comment]
Hey @plo2022 we can keep the conversation here now, no worries.

why do you have `"platform": "Connexoon"` in the last line? That's not correct, you should remove that line.

Also do make sure your email and password are not between chevrons. The chevrons are just to indicate that it's a template and you should put your own value. Just between double quotes.

**Comment by lint2015** [comment]
@plo2022 I assume since you’re in AU you’ve got the Conexoon RTS hub? In addition to what @yenoiwesa suggests, I think you also need to change the service to “ConnexoonRTS.”

**Comment by plo2022** [comment]
hey everyone - not sure what's going wrong here - no idea why the extra line is appearing. I uninstalled the plugin, reinstalled (copy/pasted the exact code from the configuration instructions - no extra line, added username and pw and changed service to ConnexoonRTS), restarted, got the same error, went back into the plugin and the extra line is back!

**Comment by yenoiwesa** [comment]
Your JSON file must be malformed @plo2022, validate it with a website such as https://jsonlint.com

**Comment by plo2022** [comment]
tried that @yenoiwesa - says it's valid with or without the extra lines.....do you know of anyone who can set this up for me?

**Comment by yenoiwesa** [comment]
@plo2022 could you please start your homebridge server in debug mode, adding the command line argument `-D` when you start it, and paste here the exact error that you have in the logs.

**Comment by plo2022** [comment]
```
[01/02/2022, 6:38:57 am] [Homebridge UI] Error: listen EADDRINUSE: address already in use :::8581
[01/02/2022, 6:38:57 am] [Homebridge UI] Another process or service on this host is using port 8581.
[01/02/2022, 6:38:57 am] [Homebridge UI] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[01/02/2022, 6:38:57 am] [Homebridge UI] Ending process now.
```
Thanks

**Comment by yenoiwesa** [comment]
@plo2022 the error is quite clear that you have another process running already using port 8581 on your system. I feel like I won't be able to help you a lot more. I recommend following a Homebridge tutorial and also googling errors that you encounter.

**Comment by plo2022** [comment]
Will look into it - thanks for your help @yenoiwesa

**Comment by lint2015** [comment]
Without knowing your setup, try restart the device Homebridge is running on in case the port wasn't released properly from a previous instance. If the port is still not available, you'll have to find out which service is using the port and turn it off, or change your Homebridge port.

**Comment by yenoiwesa** [comment]
@plo2022 is your problem resolved now?

**Comment by yenoiwesa** [comment]
I will close the issue for now, feel free to reopen if you have more info.
