### ISSUE TITLE
Add supported devices

### ISSUE THREAD

**Issue by hoefs** [yenoiwesa/homebridge-connexoon#4]
Hi,
I am planning to add a Connexoon for 3x roll down shutters and 1x Folding arm awning. All connection with IO to a Connexoon. Will they be supported by default by your package or can you add them?

**Comment by yenoiwesa** [comment]
Hi @hoefs,

What type of Connexoon device do you intend to buy? Is that an RTS Connexoon or using another protocol?

Currently the codebase is mapping all **Screen** type devices to a Homekit **Window Covering**. So I'd say yes but I don't have the mean to actually test what's coming back from the API for these specific accessory types.

https://github.com/yenoiwesa/homebridge-connexoon/blob/master/src/services-mapping.js

Also it seems that your geographic region is Europe, which I am not sure this plugin's login mechanism handles correctly. I reverse engineered the Australian/Singapore Somfy app for its login access token and it's possible that a different one be used on the European market.
I will need to verify that and update the `README` if it happens that this plugin is specific to the APAC market.

Thanks!

**Comment by yenoiwesa** [comment]
Hi @hoefs,

Support for Roller Shutters has been added in `v1.2.0` of this plugin. Regarding folding arm awnings I would need you to try the plugin first and then I can debug if it does not work.

Cheers,
Matt

**Comment by hoefs** [comment]
> Hi @hoefs,
> 
> Support for Roller Shutters has been added in `v1.2.0` of this plugin. Regarding folding arm awnings I would need you to try the plugin first and then I can debug if it does not work.
> 
> Cheers,
> Matt

Hi Matt, I will let you know when my connexoon io gets installed.
Thx  for the support.
Look like Somfy dropped the homekit development again from their website.

**Comment by yenoiwesa** [comment]
I will close this issue as support for IO devices is tracked in #6 already
