### ISSUE TITLE
Plugin fails with CERT_HAS_EXPIRED error

### ISSUE THREAD

**Issue by farryston** [yenoiwesa/homebridge-connexoon#40]
Hi 

If you can assist me please, Connexoon was working fine but sudeently I got this error 
![image](https://user-images.githubusercontent.com/98724121/151733311-02ae938d-124f-4c3f-b4a6-2dc6c3693684.png)
Regards

**Comment by yenoiwesa** [comment]
Hi @farryston 👋 

Could you check for me which version of node.js you are using?

**Comment by yenoiwesa** [comment]
Also can you check that the system's clock is correct?

**Comment by Kositch** [comment]
Hello, I have this issue as well since this night - see screenshot, after a few hours it caused to stop whole Homebridge instance running.
![AE552783-74B0-4E32-98A0-791F571E0CDB](https://user-images.githubusercontent.com/86477937/151745125-c4b6cd13-c93f-4463-a4be-f92645454173.png)

**Comment by yenoiwesa** [comment]
Just tried restarting homebridge with the plugin myself, it's working fine.

Please do the same as above @Kositch and report your node js version and verify if your system's clock is correct.

**Comment by Kositch** [comment]
> Just tried restarting homebridge with the plugin myself, it's working fine.
> 
> Please do the same as above @Kositch and report your node js version and verify if your system's clock is correct.

Hello, I have restarted whole Rapsberry PI with Homebridge and it did not solve the issue - at first it seemsit was not reporting the issue with certificate and it only reported that No Devices are associated and after a few minutes it started telling the error with certificate again, Node JS version is 16.13.2., system time and date is correct. It stopped out of nothing - no updates between the working and not working state. Couldn't it be Conexoon server side issue?

**Comment by yenoiwesa** [comment]
@Kositch it could be, I am not able to reproduce the issue myself. It is able to list devices from the Somfy API just fine. What `service` are you using?

**Comment by Kositch** [comment]
> @Kositch it could be, I am not able to reproduce the issue myself. It is able to list devices from the Somfy API just fine. What `service` are you using?

Conexoon

**Comment by yenoiwesa** [comment]
Yeah this is not the same service I use for my own blinds in Australia so really I don't know :-/ All the URLs for the other services are based off https://github.com/dubocr/homebridge-tahoma

**Comment by yenoiwesa** [comment]
Can you control your shades through the Somfy app?

**Comment by Kositch** [comment]
> Can you control your shades through the Somfy app?

Tried on .apk emulator (Connexoon RTS app not available in my country), logged in, all my Windows present and yes, I can control them through the app without an issue 🤷‍♂️
![00D6894A-72D6-4B02-822E-94D2CC87A497](https://user-images.githubusercontent.com/86477937/151751479-9af09961-5c8c-4340-8a12-0e4e007ba975.jpeg)

**Comment by Cardo1** [comment]
Just wished to add I’m having the same issue. Based in the UK using the Tahoma service.

**Comment by yenoiwesa** [comment]
Well I have bad news for you all, I have no way to remediate to that. It might be possible that Somfy has changed the servers its app is directing traffic to, but I do not know the new domain.

Could any of you tell me if they can control their shades with https://github.com/dubocr/homebridge-tahoma?

**Comment by manmei80** [comment]
I have the same issue since a few hours.
Service Connexoon, node version 16.13.2. controlling the Shutters through Connexoon app works.

**Comment by manmei80** [comment]
Tahoma plugin works for me

**Comment by yenoiwesa** [comment]
@manmei80 alright that's interesting then. I will need to investigate how they differ. Would you be able to tell me what URL is targeted in your case (probably with debug logging, command line argument `-D` when starting homebridge) please?

I would like to know which one of these is used in your case: https://github.com/dubocr/overkiz-client/blob/master/src/Client.ts#L14-L25

**Comment by yenoiwesa** [comment]
Also could someone try changing this line in their `node_modules/homebridge-connexoon/src/api/server.js` directory: https://github.com/yenoiwesa/homebridge-connexoon/blob/master/src/api/server.js#L4

and replace:
```js
Connexoon: 'tahomalink.com',
```
with
```js
Connexoon: 'ha101-1.overkiz.com',
```
then restart homebridge and let me know if that fixes anything?

**Comment by orianlevy** [comment]
I have the same issue in Israel!

**Comment by manmei80** [comment]
Sorry I am new in hoobs. I must figure out how to access debug mode. Sorry

**Comment by vandinter** [comment]
the problem is quite simple: tahomalink.com ssl certificate expired tonight, so we need to wait on somfy to renew the certificate. OR (NOT recommended) disable certificate check...

**Comment by Brinky-ux** [comment]
Same issue here in the Netherlands. Since this morning I get the certificate expired message in the Homebridge log and it no longer works. I tested it in the Somfy app and it also did not work at first. However after I logged out and logged in again in the Somfy app, I could control the blinds again from the Somfy app. Homebridge still presents the error though.

**Comment by yenoiwesa** [comment]
I assume `tahomalink.com` is on the way out @vandinter so even disabling certificate verification might only end up being a temporary patch.

Please can any of you try to install the following branch of the plugin and let me know how it goes:

```
npm install -g "https://github.com/yenoiwesa/homebridge-connexoon.git#8d1da48adc3f395638a0b85b0ea9df074d29646f"
```

I replaced the `tahomalink.com` domain by `ha101-1.overkiz.com`.

**Comment by HomekitDave** [comment]
> I assume `tahomalink.com` is on the way out @vandinter so even disabling certificate verification might only end up being a temporary patch.
> 
> Please can any of you try to install the following branch of the plugin and let me know how it goes:
> 
> ```
> npm install -g "https://github.com/yenoiwesa/homebridge-connexoon.git#8d1da48adc3f395638a0b85b0ea9df074d29646f"
> ```
> 
> I replaced the `tahomalink.com` domain by `ha101-1.overkiz.com`.

@yenoiwesa This has resolved the issue.

**Comment by yenoiwesa** [comment]
Awesome @HomekitDave ! Thanks a lot for testing that. I am eating dinner at the moment but will merge and release a new patch version on npm shortly after.

**Comment by vandinter** [comment]
> I assume `tahomalink.com` is on the way out @vandinter so even disabling certificate verification might only end up being a temporary patch.
> 
> Please can any of you try to install the following branch of the plugin and let me know how it goes:
> 
> ```
> npm install -g "https://github.com/yenoiwesa/homebridge-connexoon.git#8d1da48adc3f395638a0b85b0ea9df074d29646f"
> ```
> 
> I replaced the `tahomalink.com` domain by `ha101-1.overkiz.com`.

Works for me as well! Thanks yenoiwesa!!

**Comment by farryston** [comment]
@yenoiwesa  , works for me as well. Thank you so much :)

**Comment by yenoiwesa** [comment]
Thanks @vandinter and @farryston for your testing too!

I just released version `2.1.2` of the plugin with the fix, please upgrade to the final version:

```
npm install -g homebridge-connexoon@~2.1.2
```

This fixes the certificate expired error by changing the domain name that is accessed.

**Comment by manmei80** [comment]
Thank you, also works for me again!

**Comment by jdebardi** [comment]
I was about to update to 2.1.2 and then it started working again on it's own, so I guess Somfy have updated the cert now for the original domain anyway.

**Comment by yenoiwesa** [comment]
@jdebardi haha indeed Somfy just renewed the certificate. The start date of the new one is today:
![4071F1F2-6D7A-45F3-ADFD-BCA3D39EEA4F](https://user-images.githubusercontent.com/1464666/151782413-5926edd7-4f8c-40ab-b23b-ef1d1168aa50.jpeg)

**Comment by yenoiwesa** [comment]
I still recommend upgrading the plug-in and using the new domain 😀

**Comment by Kositch** [comment]
Thank you for quick solution! Works like a charm 👍
