### ISSUE TITLE
Hoobs insist i have update although the plugin is up-to-date

### ISSUE THREAD

**Issue by orianlevy** [yenoiwesa/homebridge-connexoon#43]
Hi,
Since the last update (2.1.2), hoobs check-for-update insist i have update to the plugin although its up-to-date.
And of course when you click update nothing happens because its already updated.
But the issue is when i have other relevant updates its blocking them.
Can you please assit?
NOTE: I tried to uninstall and install the plugin fresh but that dosent solve this issue.

![Screen Shot 2022-02-10 at 13 39 39](https://user-images.githubusercontent.com/16107433/153401750-89119537-3ce5-4092-a896-8cc8509192c6.png)
![Screen Shot 2022-02-10 at 13 39 45](https://user-images.githubusercontent.com/16107433/153401753-222cc45d-e6e3-4112-aadf-1a1f3ae81e7a.png)

**Comment by yenoiwesa** [comment]
Hi @orianlevy have you talked to HOOBS support? Version 2.1.2 of the plugin exists and is available on npm: https://www.npmjs.com/package/homebridge-connexoon/v/2.1.2

I don't think there is anything I can do about your problem from my end.

**Comment by orianlevy** [comment]
i know, i have the latest plugin version 2.1.2 installed. 
but hoobs still think i have to update

**Comment by yenoiwesa** [comment]
You'll have to contact HOOBS then.

**Comment by orianlevy** [comment]
i found a solution here:
https://github.com/hoobs-org/HOOBS/issues/1590

**This happens when a plugin is out of place. This has been fixed. Run this command in the terminal to fix.
sudo rm -fR /var/lib/hoobs/hub/node_modules && sudo rm -f /var/lib/hoobs/hub/package.json && sudo hoobsd service restart**

**Comment by yenoiwesa** [comment]
Cheers thanks for posting the solution here @orianlevy !
