### ISSUE TITLE
Multiple Connexoon devices supported?

### ISSUE THREAD

**Issue by robimart** [yenoiwesa/homebridge-connexoon#44]
Hi there 

Love this plugin, it’s a big part of my automated home! I’m curious whether it supports multiple Connexoons being chained together to give wider coverage in a large house? Or it’s limited to 1 unit only?

(not sure of this is the right place to ask questions couldn’t find anywhere else)

thanks in advance!

robin

**Comment by yenoiwesa** [comment]
Hi @robimart 👋 

I am glad you're enjoying the plug-in!
A similar question was raised recently, have a look at: https://github.com/yenoiwesa/homebridge-connexoon/issues/38

TL;DR is that the plug-in does not support multiple Connexoons but Somfy sells RTS signal extenders for that purpose.

**Comment by robimart** [comment]
Thank you so much for the quick reply and apologies for the duplicate query. I’ll look into that!

**Comment by yenoiwesa** [comment]
No worries, I will close the issue then :-)
