### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by Valdemar1111** [yenoiwesa/homebridge-connexoon#50]
Can you show me, example of config file please.

name, it is email address ?

```
{
    "bridge": {
        "...": "..."
    },
    "description": "...",
    "platforms": [
        {
            "platform": "Connexoon",
            "name": "My Connexoon Hub",
            "username": "<*****************@gmail.com",
            "password": "<*********>",
            "service": "Connexoon"
        }
    ],
    "platform": "Connexoon"
}
```

what is incorrect? and how I can ad devises ?

**Comment by yenoiwesa** [comment]
Hi @Valdemar1111 👋 

The `username` should be your Somfy account user name that you used when you setup the Somfy Connexoon hub via the mobile app. Generally your email address.

As to how to add devices, the platform will automatically add all the window coverage devices that have been mapped to your Somfy Connexoon hub.

I'll close this issue as answered. Feel free to reopen if you have more questions.

**Comment by Valdemar1111** [comment]
[Connexoon] Username and password must be defined as configuration.
[Connexoon] Failed to get device list undefined
[Connexoon] Could not initialise platform, will retry in 5 min


 I read all the closed topics, but did not find a solution, I still have no way to log in.

can you help?

**Comment by Valdemar1111** [comment]
everyone has problems because of the region, I tried all the options for the service, but it did not help.

I am in Russia

**Comment by yenoiwesa** [comment]
The error message clearly says that the username and the password must be defined in your configuration. If it's not how do you expect it can work?

Check your configuration for username and password as clearly it's not properly defined/not present.

**Comment by Valdemar1111** [comment]
{
    "bridge": {
        "...": "..."
    },
    "description": "...",
    "platforms": [
        {
            "platform": "Connexoon",
            "name": "My Connexoon Hub",
            "username": "xxxxxxxxxxxx@gmail.com",
            "password": "xxxxxxx",
            "service": "Connexoon"
        }
    ],
    "platform": "Connexoon"
}

it is my configuration, username and password is correct

Whatever data I enter is correct or incorrect, the error text does not change, please check if everything is correct in my configuration

**Comment by Valdemar1111** [comment]
I have Connexoon RTS

**Comment by yenoiwesa** [comment]
@Valdemar1111 you have a second "platform": "Connexoon" at the bottom of your configuration. That's incorrect. Remove it.

**Comment by Valdemar1111** [comment]
I don't add it, it acts on its own every time, even if I remove it

**Comment by Valdemar1111** [comment]
<img width="2560" alt="Снимок экрана 2022-03-27 в 09 28 13" src="https://user-images.githubusercontent.com/75220483/160269526-006d472e-0adb-4d34-89ef-f2aa81faf94a.png">
}

**Comment by Valdemar1111** [comment]
I delete it, click save, go back to the settings window and it's there again...

**Comment by yenoiwesa** [comment]
Your configuration makes no sense in that screenshot. Why do you have the bridge, the description, all with ellipsis value (clearly meant to say it's a template).

I don't know how to use homebridge config UI, I don't use it myself, but you need to read more about homebridge and understand what is a platform...

Only put the JSON object that corresponds to the platform you are configuring, not the outer objects that are meant to represent how to configure a normal homebridge configuration file.

**Comment by yenoiwesa** [comment]
Clearly the UI is giving you a hint by adding the platform bit every time...
