### ISSUE TITLE
Open/my/close issue

### ISSUE THREAD

**Issue by fcXesco** [yenoiwesa/homebridge-connexoon#54]
Hi! Thanks in advance for this plugin! My issue is that I can only wholly open or close my awnings. In homekit, I get this slider

![image](https://user-images.githubusercontent.com/104967535/167091180-1be7aed9-08bc-4183-be90-bb89d30c64b1.png)

but it does not allow to stop the awning in the middle. I have tried to use the commands configuration but it seems does not work

**"3": {
                    "commands": [
                        "close",
                        "my",
                        "open"
                    ]
                }**

**Comment by yenoiwesa** [comment]
This list of commands is the default so you can completely remove that block, it does nothing.

I assume you just haven't set your my position on the blind.

**Comment by fcXesco** [comment]
(commands out).
Hi again (you were right, I had not set 'my' before). Now I have set 'my' button, so if I place the slicer in the middle, it works like the 1st press in 'my' button, placing the awning in a specific position, but it **does not work** as a 'stop' button as it does in the remote control (which is my goal).
Could it be possible to replace the slicer in home app with something else similar to the remote control (does it exist)?
![image](https://user-images.githubusercontent.com/104967535/167172521-cd1f568a-911c-493d-be7f-e1e9659e245e.png)

**Comment by yenoiwesa** [comment]
Hi @fcXesco, there is no mapping in HomeKit to stop blinds since blinds are supposed to go to a given position, but the RTS protocol is a one way protocol and thus the remote (the Connexoon) cannot know at what position the blind is.

I have had requests to implement separate stop buttons as switches in HomeKit in the past, but I have closed them since I don't feel this belongs in the plugin. I do not intend to implement such feature.

Hope that answers your question!

Cheers.

**Comment by fcXesco** [comment]
It would just add a similar button you see in the following image (which belongs to my fan), which allows stopping the awnings anytime. 
![image](https://user-images.githubusercontent.com/104967535/167243261-2ed32d21-c685-4870-9293-3852334a4c3b.png)
There is no need to know what position the awning is. What I am looking for is to stop it anytime. I am sure this button also responds to other requests you have had in the past! I hope you would intend to implement it. Many thanks in any case for your time! Regards from Barcelona

**Comment by jdebardi** [comment]
The problem is Apple decide that interface! So go and ask Apple.

**Comment by yenoiwesa** [comment]
Yeah @jdebardi said it. A window covering service cannot have a stop button in HomeKit. This is just not how it works.

**Comment by fcXesco** [comment]
Understood :-( thanks everybody!
