### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by tkilik11** [yenoiwesa/homebridge-connexoon#55]
![A720C0E9-ED3A-4FF1-A971-EF3BFD98D145](https://user-images.githubusercontent.com/85321089/167526902-f555ab34-de98-40f5-a0dc-7e8359a0eede.jpeg)
![4D4785D1-4F1C-458C-97B3-F4441AC365E6](https://user-images.githubusercontent.com/85321089/167526916-60e97b73-a6f6-4694-946a-e8c5c1e1bbc2.jpeg)

Seem to be getting this issue out of no where

any ideas?

**Comment by yenoiwesa** [comment]
Yeah you got banned for too many invalid connections to the Somfy API. Might be due to the recent outage Somfy had. Either way, you should turn off the plugin for a couple of days until the temporary ban ends.
See: https://github.com/yenoiwesa/homebridge-connexoon/issues/52

**Comment by BladesKnight** [comment]
Yeah, I am getting this error out of nowhere too. Has been working for years and then... poof!

Will disable the plugin for the time being and let it reset itself.

**Comment by yenoiwesa** [comment]
That sucks, but there is nothing I can do about it on my end :-/

**Comment by shazport** [comment]
Hi,

Can I have some help with logging in please. I have checked my credentials with the app on phone and it loggs in sucessfully.

Not sure I have the setup correct!!!

Thanks


6/7/2022, 11:11:52 AM] [My Connexoon Hub] Failed to get device list { errorCode: 'AUTHENTICATION_ERROR', error: 'Bad credentials' }
[6/7/2022, 11:11:52 AM] [My Connexoon Hub] Could not initialise platform, will retry in 5 min
[6/7/2022, 11:16:52 AM] [My Connexoon Hub] Failed to login { errorCode: 'AUTHENTICATION_ERROR', error: 'Bad credentials' }
[6/7/2022, 11:16:52 AM] [My Connexoon Hub] Failed to get device list { errorCode: 'AUTHENTICATION_ERROR', error: 'Bad credentials' }
[6/7/2022, 11:16:52 AM] [My Connexoon Hub] Could not initialise platform, will retry in 5 min
[6/7/2022, 11:21:53 AM] [My Connexoon Hub] Failed to login { errorCode: 'AUTHENTICATION_ERROR', error: 'Bad credentials' }

!
![Capture](https://user-images.githubusercontent.com/107011332/172279461-d76900ff-3839-494e-817c-79f788a32714.JPG)

**Comment by yenoiwesa** [comment]
@shazport remove the `<` and `>` characters around your username and password 😁

**Comment by shazport** [comment]
Awesome – all working thanks

**Comment by yenoiwesa** [comment]
Reminds me that I need to close this issue as there is nothing I can do about the original reported problem.

**Comment by shazport** [comment]
Hi - any suggestions why I'm getting these messages. I have removed all the additional blinds from the somfy app and restarted HB?
Thanks
John


[Image.jpeg]
________________________________
