### ISSUE TITLE
Failed to get device list - some strange code in HB log

### ISSUE THREAD

**Issue by Kositch** [yenoiwesa/homebridge-connexoon#56]
Hello, 

until today it worked since last crash and banning issue, but today I get this strange errors in HB log, after a while it even caused the HB to reboot:

![2022-05-10_10-19-57](https://user-images.githubusercontent.com/86477937/167582930-d65d4150-be82-47a6-9520-56fecaf2de4b.png)

**Comment by yenoiwesa** [comment]
Lol well, seems like their server is down and they are sorry for the inconvenience.

Somfy....

**Comment by Kositch** [comment]
OK, so no issue on my side, lets see if I get the ban again :D

**Comment by Kositch** [comment]
Now it is working again without ban, you can close it. Thanks.
