### ISSUE TITLE
Error code: Resource access denied.  Too many attempts with invalid token.  Temporarily banned

### ISSUE THREAD

**Issue by woodgieboodgie** [yenoiwesa/homebridge-connexoon#57]
Hello,

Plugin was working fine and has started to error with statement:

Error code: Resource access denied.  Too many attempts with invalid token.  Temporarily banned.

No password has been changed and Connexoon is on the network responding as expected.

{
    "platform": "Connexoon",
    "name": "My Connexoon Hub",
    "username": "**********@*******.com",
    "password": "*************",
    "service": "ConnexoonRTS"
}

**Comment by yenoiwesa** [comment]
Please see https://github.com/yenoiwesa/homebridge-connexoon/issues/55
