### ISSUE TITLE
Unable to start Connexoon: Username and password must be defined as configuration

### ISSUE THREAD

**Issue by Haapie** [yenoiwesa/homebridge-connexoon#60]
Hello @yenoiwesa

If have searched already in the closed issues, but couldn't find the answer to my problem.

When connecting to homebridge Connexoon I get the following reply:

[17/06/2022, 13:14:18] Loading 2 platforms...
[17/06/2022, 13:14:18] [Config] Initializing config platform...
[17/06/2022, 13:14:18] [Config] Running in Service Mode
[17/06/2022, 13:14:18] [Connexoon] Initializing Connexoon platform...
[17/06/2022, 13:14:18] [Connexoon] Connexoon Init
[17/06/2022, 13:14:18] [Connexoon] **Username and password must be defined as configuration.**
[17/06/2022, 13:14:18] [Connexoon] **Failed to get device list undefined**

My config:

        {
            "bridge": {
                "...": "..."
            },
            "description": "...",
            "platforms": [
                {
                    "platform": "Connexoon",
                    "name": "My Connexoon Hub",
                    "username": "******@*****.nl",
                    "password": "****************",
                    "service": "ConnexoonRTS"
                }
            ],
            "platform": "Connexoon"

Is there something missing? 

Thanks!!

**Comment by yenoiwesa** [comment]
Hi @Haapie ,

Remove the last line it's wrong.

**Comment by Haapie** [comment]
Hi @yenoiwesa 

Thank you for your quick reply, I appreciate it!

Unfortunately it doesn't solve the problem, I already tried. This is mark-up from the editor, because I copied your information from the README-file.

The reply I get in de config-editor when I remove the line is _all platform blocks must contain the "platform" attribute_  

I included the whole (edited) config-file.
<img width="1306" alt="Schermafbeelding 2022-06-17 om 15 47 06" src="https://user-images.githubusercontent.com/107685576/174312238-4835e90d-58a0-4f2f-bfd7-92c809aaaf18.png">

**Comment by yenoiwesa** [comment]
Hey @Haapie, that configuration is even more wrong than I thought haha.

Do you see how you are defining a bridge and a description with placeholder `...` values in the platform's configuration? That was meant to be an example for people to know where to put the JSON in the file not to copy paste in their platform configuration lol.

Just remove that red highlighted block entirely and replace it with just the JSON object that corresponds to the actual Connexoon platform, the one with the 5 entries.

**Comment by Haapie** [comment]
Haha...my mistake. A real newby-thing lol
Thank you! 

Problem solved, but ......another problem appears.

![image](https://user-images.githubusercontent.com/107685576/174442820-d0f516e0-500a-4d56-b6f9-2c7677448165.jpeg)

_RESOURCE-ACCES-DENIED, unknown user_, while this is the email address I use to log in to my Somfy account.

Probably a change of service, like issue 9? Maybe Europe (Netherlands) is _TaHoma_ as service. I'm away for the weekend now, so I'll give it a try tomorrow.

Thanks again for your help (and patience lol) and of course all the time you put into developing this!

**Comment by yenoiwesa** [comment]
Yes you will have to try the other services. `ConnexoonRTS` is mostly used for the Asia Pacific market (I am in Australia).

Give a try to the other values until you find one that does work.

**Comment by yenoiwesa** [comment]
I updated the plugin to version `2.2.1` with support for config UI schema, which means you should now be able to configure the plugin via UI instead of JSON after the upgrade.

I trust you will find the right service to use for your region/market so I'll now close this issue. Feel free to comment if you are still having problems.

**Comment by Zeses** [comment]
Hi Yenoiwesa, I installed your latest version but I don't get promoted with a UI config page all I see is this, any ideas?

{
    "platform": "Connexoon",
    "name": "Connexoon"
}

<img width="1168" alt="Screen Shot 2023-03-09 at 1 37 43 pm" src="https://user-images.githubusercontent.com/4159881/223901872-d84ef5af-9fa5-4bd4-b431-670514deadd3.png">

**Comment by Zeses** [comment]
im also in Australia so im hoping all I need to do is add my credentials ?

**Comment by yenoiwesa** [comment]
Hey @Zeses 👋 It would be better to open a new issue than commenting on an old closed one.
The plugin has the necessary schema files to offer an admin UI normally so I am surprised it doesn't offer it to you. Either way, all the details on the configuration object shape are documented in the readme file: https://github.com/yenoiwesa/homebridge-connexoon

**Comment by Zeses** [comment]
ah sorry about that, I can delete it and re create a new issue if you like?

im not really a developer and don't know Json  

If you were able to have a copy of a dummy config were newbies like me can just copy and paste (or have it as default in the startup config)  it and replace the credentials it would much appreciated..

**Comment by yenoiwesa** [comment]
It's there in the README file:

```json
{
  "platform": "Connexoon",
  "name": "Connexoon",
  "username": "blahblah@blah.com",
  "password": "more blah blah"
}
```

**Comment by Zeses** [comment]
ok, it now logs in successfully to the server with no credential errors, but its not pulling/showing any of the devices though..

**Comment by yenoiwesa** [comment]
That's when you should create a new issue :-)

**Comment by Zeses** [comment]
Ha! will do :)
