### ISSUE TITLE
Just only one shutter

### ISSUE THREAD

**Issue by MasterofKungfu9999** [yenoiwesa/homebridge-connexoon#63]
I set up Connexxon, entered the correct credentials and got a device displayed. Now I have expanded my configuration to include several devices, but I still only see one device. I cleared the cache, uninstalled the plugin but nothing helped. One device keeps popping up. All other devices are not displayed.

I use hoobs und the tahoma plugin.

Best regards

**Comment by yenoiwesa** [comment]
Well sorry @MasterofKungfu9999 but this is not the Tahoma plugin's repository.

Were you looking for: https://github.com/dubocr/homebridge-tahoma

**Comment by MasterofKungfu9999** [comment]
@yenoiwesa 

Yes, I know that, but the problem occurs when using Connexxon

**Comment by yenoiwesa** [comment]
Can you please provide more information. Steps you have taken, your current Homebridge configuration, your past homebridge-connexoon platform configuration, the accessories you have in the Somfy app, screenshots, etc.

**Comment by yenoiwesa** [comment]
I have not received a response from you so I will close the issue. Feel free to reopen.
