### ISSUE TITLE
Plugin not working for me

### ISSUE THREAD

**Issue by Kooka71** [yenoiwesa/homebridge-connexoon#71]
I am new to GitHub and Homebridge. I have all my Plugins working except this one.
I have over written username & Password but is there something else I should try?

**Comment by Kooka71** [comment]
I hav a working Connexoon and I am based in Australia

**Comment by yenoiwesa** [comment]
Hi @Kooka71,

Do you have any more details for me? Logs or something? Not much I can work with here.

**Comment by Kooka71** [comment]
All sorted!
User error!

I am a complete novice and day one of Homebridge. It is now working perfectly!

By the way, would you recommend a Child Bridge always?

Sent from my iPhone

On 18 Dec 2022, at 11:36 am, Matthieu Di Berardino ***@***.***> wrote:

﻿

Hi @Kooka71<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKooka71&data=05%7C01%7C%7C11fda3dedbe3470e5e7008dae08fe2c1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638069205836542514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cr2bxSICLIH2zMDKKHfl7uR3Ot01pXa%2BcyCWPIsdmYg%3D&reserved=0>,

Do you have any more details for me? Logs or something? Not much I can work with here.

**Comment by yenoiwesa** [comment]
Haha no worries, glad to know it's now working fine.

What do you mean by child bridge?
