### ISSUE TITLE
Connexoon plugin failing out of the blue

### ISSUE THREAD

**Issue by gagakrimang** [yenoiwesa/homebridge-connexoon#75]
Been using the Connexoon plugin without issues for the past couple of months. Out of the blue yesterday, it shows no response on my Home app.

Here are the things I did:

1. Logged out and logged in to controlled my blinds via the Somfy app - Successful
2. Logged in via www.somfy.com.sg/login - Successful
3. Restarted Homebridge - failed
4. Uninstalled Connexoon plugin and reinstalled and putting in all correct credentials - failed

Every time it fails, it shows this error:

[Connexoon] Logged in successfully via Somfy OAuth
[1/20/2023, 10:17:47 AM] [Connexoon] Failed to get device list {
  errorCode: 'RESOURCE_ACCESS_DENIED',
  error: 'Too many attempts with an invalid token, temporarily banned.'
}
[1/20/2023, 10:17:47 AM] [Connexoon] Could not initialise platform, will retry in 5 min

**Comment by yenoiwesa** [comment]
We've seen this in the past. The TL;DR is that the Somfy server probably went down (for maintenance or an incident) and the plugin tried to reconnect while it was down. Eventually the service went back up but Somfy recorded the many login attempts as suspicious and your account got banned (when logging in with the specific access token the plugin uses).

The only option now is to wait a bit before re-enabling the plugin (24 hours or so).

**Comment by jdebardi** [comment]
Mine is also stuck - it's what prompted me to make this comment https://github.com/yenoiwesa/homebridge-connexoon/issues/74#issuecomment-1397210055 as it would solve Somfy's less than stellar server availability.

**Comment by ThomasK78** [comment]
Hello,
same problem.

**Comment by yenoiwesa** [comment]
Yep sorry guys as usual, can't help with that unfortunately. You'll just have to wait.

**Comment by ThomasK78** [comment]
Hi,Yes i am waiting 😂But thank u for this nice plugin. I am using it for long time. For RTS there are not so much plugins available. Greetings from Saarland Germany Von meinem iPad gesendetAm 21.01.2023 um 22:36 schrieb Matthieu Di Berardino ***@***.***>:﻿
Yep sorry guys as usual, can't help with that unfortunately. You'll just have to wait.

**Comment by yenoiwesa** [comment]
Is the issue fixed for you all now? Can I close the issue?

**Comment by jdebardi** [comment]
Yep, once I disabled the plugin for 24h it all worked again.

**Comment by yenoiwesa** [comment]
Thanks @jdebardi
