### ISSUE TITLE
Unable to obtain device list homebridge-connexoon

### ISSUE THREAD

**Issue by Zeses** [yenoiwesa/homebridge-connexoon#80]
Having issues obtaining the device list

[09/03/2023, 15:45:48] [Connexoon] Failed to get device list Error: connect ETIMEDOUT 51.79.201.96:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '51.79.201.96',
  port: 443

**Comment by Zeses** [comment]
Actually now I can see the devices, seems to take a while after a reset, but on the Apple Home app when I select any of the blinds it states No Response

**Comment by Zeses** [comment]
I also tried opening from the Homebridge but its stuck at opening 

<img width="923" alt="Screen Shot 2023-03-09 at 3 51 10 pm" src="https://user-images.githubusercontent.com/4159881/223920880-d1f68720-6dbd-4f44-8fd4-1549a28385e0.png">

**Comment by yenoiwesa** [comment]
What happened why is it now closed? Lol

**Comment by Zeses** [comment]
It just started working 🤦‍♂️ I swear I made no changes… 🤷‍♂️RegardsZeses0418691724On 9 Mar 2023, at 7:36 pm, Matthieu Di Berardino ***@***.***> wrote:﻿
What happened why is it now closed? Lol

**Comment by yenoiwesa** [comment]
Haha alright then.
