### ISSUE TITLE
Username error

### ISSUE THREAD

**Issue by holman8a** [yenoiwesa/homebridge-connexoon#83]
Hi there,

Firstly thanks for all the work in setting this up, sure it'll be amazingly useful when I get it all working! 

This is actually my first time using Homebridge so apologies if I've stuffed something basic up! 
I've got this all downloaded, however get the below error message in my logs:

[3/19/2023, 1:38:59 PM] [Connexoon] Failed to get device list {
  errorCode: 'RESOURCE_ACCESS_DENIED',
  error: "Unknown user : '<removed>'"
}

My config is this:
{
    "platform": "Connexoon",
    "name": "Connexoon",
    "username": "<removed>",
    "password": "<removed>",
    "service": "Connexoon",
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": <removed>
    }
}

Note that I have signed in/out of my connexoon account to validate the username and password are correct and they're all fine. The bridge username I haven't touched. Welcome any thoughts :) 

Thanks!

**Comment by yenoiwesa** [comment]
Hi there :-)

This is the same as https://github.com/yenoiwesa/homebridge-connexoon/issues/82 so I will close this issue in favour of the other one thanks.
