### ISSUE TITLE
Percentage of RTS shutters

### ISSUE THREAD

**Issue by Twox0** [yenoiwesa/homebridge-connexoon#85]
Hello, I have a question about a feature but I haven't found the possibility of doing it. It concerns the time (in seconds) taken to lower or raise the shutters in order to be able to calculate the precise percentage of RTS shutters. I think it's an interesting feature, but is it possible? Thanks in advance, and have a good day.

**Comment by yenoiwesa** [comment]
Hey @Twox0, this is a feature I wanted to implement early on but found that the speed at which Somfy motors operate is not constant and linear enough to have time based opening work reliably.

On top of this there is an extra hurdle with the Somfy API: you cannot control the time it takes for the command to reach the Somfy server, the command being taken into account, and then the request being sent back to the device in your home. It can vary a lot and that made it impossible to work with at all.

So I gave up on the idea 😢
