### ISSUE TITLE
Username and password must be defined as configuration.

### ISSUE THREAD

**Issue by Itachi88** [yenoiwesa/homebridge-connexoon#92]
Hi sir!

I’m getting this error when copying your file. I’m looking and changing for 3 hours now but can’t find the problem. Can you help? Much appreciated!

This is what I’ve filled in:

![IMG_7346](https://github.com/yenoiwesa/homebridge-connexoon/assets/173856899/b38d5d52-7f6f-4c25-95f0-c2591390b6b0)

**Comment by Itachi88** [comment]
No one there?

**Comment by yenoiwesa** [comment]
Hello there.
I am not sure what you are showing but I am very sure that copying dummy lines like you did makes no sense at all. Ellipsis here means "there is text here, which does not matter for this context".

Now, to try to help you, there is no context as to where you're pasting this (wrong) snippet, what is this?

This README file configuration is meant for technical users that can modify the JSON configuration of their home bridge server.

**Comment by OpalSnow** [comment]
Problem has been resolved. It was caused by invalid json format.
