### ISSUE TITLE
[Connexoon] Failed to get device list Error: Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by Kositch** [yenoiwesa/homebridge-connexoon#93]
Hello,

today out of sudden Connexoon plugin platform cannot be initialized because of error below. All blinds are as Not responding in Home app. I have rebooted homebridge server, plugin running in child bridge, not resolved. Everything worked till today without any issues, no update performed prior this issue. Internet connection is OK, LED on Connexoon bridge is green indicating it has connection to the internet. Plugin version v2.2.4.

**Plugin Config:**

{
    "platform": "Connexoon",
    "name": "Connexoon",
    "username": "xxxx",
    "password": "xxxx",
    "service": "Connexoon",
    "useListedDevicesOnly": true,
    "devices": {
        "Pokojicek": {
            "commands": [
                "open",
                "close",
                "my"
            ]
        },
        "Pracovna": {
            "commands": [
                "open",
                "close",
                "my"
            ]
        },
        "Loznice": {
            "commands": [
                "open",
                "close",
                "my"
            ]
        },
        "Kuchyne": {
            "commands": [
                "open",
                "close",
                "my"
            ]
        },
        "Obyvak": {
            "commands": [
                "open",
                "close",
                "my"
            ]
        },
        "Hosti": {
            "commands": [
                "open",
                "close",
                "my"
            ]
        }
    },
    "_bridge": {
        "username": "0E:B6:43:BB:D2:DB",
        "port": 39392
    }
}

**Environment**
OS: Mac OS 14.6.1
Node.js: v20.17.0
Homebridge version: 1.8.4
NPM version: 10.8.2
Node.js Path: /usr/local/bin
Homebridge location: /Users/michal/.homebridge
Config location: /Users/michal/.homebridge/config.json
Plugin location: /usr/local/lib/node_modules

Not sure what to do.

Thanks for any help!

**Log output (repeating each 5 minutes):**

[9/24/2024, 10:45:11 AM] [Connexoon] Failed to get device list Error: Parse Error: Invalid header value char
    at TLSSocket.socketOnData (node:_http_client:551:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at TLSSocket.Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23) {
  bytesParsed: 56,
  code: 'HPE_INVALID_HEADER_TOKEN',
  reason: 'Invalid header value char',
  rawPacket: <Buffer 48 54 54 50 2f 31 2e 30 20 35 30 33 20 53 65 72 76 69 63 65 20 55 6e 61 76 61 69 6c 61 62 6c 65 0a 43 61 63 68 65 2d 43 6f 6e 74 72 6f 6c 3a 20 6e 6f ... 2042 more bytes>

**Comment by yenoiwesa** [comment]
Sorry @Kositch  I unfortunately have no idea what that network error could be about. Only thing that comes to mind is potentially a maintenance window on the Somfy servers, they are generally temporary.

Are you still experiencing the error now?

**Comment by Kositch** [comment]
Hello, thanks for reply - I am closing this issue, because it started working one hour afterwards. So mayby some server issue, but when I checked LED on Somfy RTS device, it was green - it means connection to servers OK.

**Comment by yenoiwesa** [comment]
Sorry I was of no help but glad the issue is resolved!
